### ISSUE TITLE
Linux: Interface without icons

### ISSUE THREAD

**Issue by kassane** [besh81/nana-creator#10]
After being able to compile on linux I saw that there were no icons on the interface.
*Preview:* 
![](http://nanapro.org/en-us/forum/index.php?u=/serve/attachment&path=5d8e49d3dd7e9.jpg)

**Comment by besh81** [comment]
To have the icons loaded properly the executable should be run from the wdir folder where the icons folder is. 
Ciao

**Comment by kassane** [comment]
I placed the binary next to the icons folder, but only the "creator.ico" file appeared in the status bar. When the interface is still without. However after looking at the code you realize that you have a quote from windows directories like "C:\".

**Comment by besh81** [comment]
Sorry I don't understand what you mean. Where is the "C:..." like string?

**Comment by kassane** [comment]
Yep. In the code there are some strings citing "C:\wdir\icons". Including ncp format files and their header conversions

**Comment by besh81** [comment]
I checked the code and actually there is a line in info.h where the image is loading from "C: .." but all the others are ok so the toolbar icons should be visible.
