### ISSUE TITLE
undefined reference to nana::adi_place when compiling

### ISSUE THREAD

**Issue by eboudrand** [besh81/nana-creator#12]
I cannot compile nana-creator with nana 1.7.4 and nana 1.7.3 under Ubuntu 20.04. It cannot find reference to adi_place. The errors messages are : 
/usr/bin/ld : obj/Release/src/creator.o : dans la fonction « creator::_init_ctrls() » :
creator.cpp:(.text+0x2ee6) : référence indéfinie vers « nana::adi_place::bind(nana::detail::basic_window*) »
/usr/bin/ld : creator.cpp:(.text+0x2f0d) : référence indéfinie vers « nana::adi_place::scheme() »

I am compiling with Code::Blocks and adi_place.cpp is missing from the project.

**Comment by besh81** [comment]
Thanks to fix this issue.
