### ISSUE TITLE
How to go about adding submenus?

### ISSUE THREAD

**Issue by s1nisteR** [besh81/nana-creator#14]
Any way to add menus under menus?

**Comment by besh81** [comment]
Hi @s1nisteR 

To add submenus you should:

1. select the menubar control

2. In the Properties panel open the Menus property clicking the button on the right
![collection](https://user-images.githubusercontent.com/16460595/93985632-a4779700-fd85-11ea-8e54-9f66d3e75932.JPG)

3. Use the dialog to add new menu items / separators. To add more levels at the menu move the selected item using the right arrow button.

Hope it helps

Ciao
