### ISSUE TITLE
The picture does not show

### ISSUE THREAD

**Issue by maxbad** [besh81/nana-creator#18]
Why is the picture not displayed after compilation?
![QQ截图20210525093612](https://user-images.githubusercontent.com/37558406/119427036-e7d33c80-bd3c-11eb-9130-f7ff76229c38.jpg)

**Comment by besh81** [comment]
To have the icons loaded properly the executable should be run from the wdir folder where the icons folder is. 
Ciao

_Originally posted by @besh81 in https://github.com/besh81/nana-creator/issues/10#issuecomment-536404326_

**Comment by maxbad** [comment]
Mine is fine, thank you
