### ISSUE TITLE
Nana-creator wont compile under linux.

### ISSUE THREAD

**Issue by rjklindsay** [besh81/nana-creator#23]
When attempting to compile, I get this error :
|error: ‘class nana::toolbar’ has no member named ‘tools_height’

This error happens in several places, including:
nana-creator/src/creator.h  Line 59
nana-creator/src/ctrls/toolbar.cpp  Line 66

I suspect it has something to do with the tools_height token defined in the xml file at: nana-creator/src/itemseditorpanel.ncp
Is there some code generator that must be run before compiling nana-creator?

**Comment by besh81** [comment]
Hi @rjklindsay 

you probably need to compile and link the develop version of nana lib.
That feature (tools_height) is not yet include in the release version.

Ciao
Gabriel

**Comment by renelindsay** [comment]
Hi Gabriel,
You are correct, it compiles correctly when using the develop branch of nana.
Thank you for the help
Rene
