### ISSUE TITLE
nana-creator runs on raspberry pi

### ISSUE THREAD

**Issue by cnjinhao** [besh81/nana-creator#5]
With two small fixes, `Nana creator` can run on raspberry pi. It is easy to make a portable program.
![Nana Creator](http://nanapro.org/en-us/forum/index.php?u=/serve/attachment&path=5c70f9c95c19c.jpg)

1, Define a guimanager pointer as a global variable.
```
guimanager *g_gui_mgr;

int main()
{
   g_gui_mgr = new guimanager;
```

2, in `guimanager::clear()`
```
//Check if it is empty
if(_cut_copy_doc)
    _cut_copy_doc.reset();
```

**Comment by besh81** [comment]
I'm so happy it work on raspberry pi too ... all thanks to nanalib ;)

Could you please give me some explanation? I don't understand why those changes.
1. Do it run out of memory?
2. _cut_copy_doc isn't a pointer so what's the meaning of if(_cut_copy_doc ) ?

Thanks

**Comment by cnjinhao** [comment]
1, widget objects must be initialized before internal objects of nana.  Because the the orders of initializations of global variables are not specified between different compiling unit, defining a widget object as a global variable is behavior undefined.

2, call `_cut_copy_doc.reset()` when `_cut_copy_doc` is empty, it occurs an assertion error. I don't know why `pugixml` doesn't allow to reset an empty object.

**Comment by besh81** [comment]
Suggested fixes added to nana creator.
Thanks @cnjinhao
