### ISSUE TITLE
Project Directory freature

### ISSUE THREAD

**Issue by r9guy** [besh81/nana-creator#6]
Can you please implement Project Directory feature. let by default Nana Creator create it's projects in %UserProfile%NanaCreator\ folder, under (internal use) folder.

**Comment by besh81** [comment]
Hi @r9guy 

right now nana creator should remember the last dir used to create a project.

Would you like to create a dir with the project name and inside the creator project file?

**Comment by r9guy** [comment]
"Would you like to create a dir with the project name and inside the
creator project file?
"
Well some kind of logical sorting would help of course
