### ISSUE TITLE
Does not build against nana 1.7.2

### ISSUE THREAD

**Issue by ppetraki** [besh81/nana-creator#7]
Lots of things are different. Once I got the project compiled it runs but all the icons for the title bar are not mapped.

https://github.com/ppetraki/nana-creator/commit/8bd331062e34751f2bbc9c76a259ed4c8da1bb25

**Comment by besh81** [comment]
Hi @ppetraki the version you are using is developed using nana 1.7.1. 
The 1.7.2 version will be available soon I'm working on it right now.
To have the icons loaded properly the executable should be run from the wdir folder.
Ciao

**Comment by ppetraki** [comment]
It would be helpful if were to setup a travis CI for this. Even if it's against an older version of the lib.
