### ISSUE TITLE
Port to mesonbuild

### ISSUE THREAD

**Issue by ppetraki** [besh81/nana-creator#8]
I don't use codeblocks nor do I have visual studio so I ported the entire project to meson.

https://github.com/ppetraki/nana-creator

Which will support creating visual studio project files and many other backends.

**Comment by kassane** [comment]
It is now possible to use cmake in the original project.
By the way, I relied on your fork to add cmakelist but made some modifications.

**Comment by ppetraki** [comment]
It "looks" OK, but it fails to build. Also, pthreads should always be last in the lib resolution list.
[ 94%] Building CXX object CMakeFiles/nana-creator.dir/home/ppetraki/Sandbox/Games/nana-creator/src/inifile.cpp.o
[ 96%] Building CXX object CMakeFiles/nana-creator.dir/home/ppetraki/Sandbox/Games/nana-creator/src/ctrls/group.cpp.o
/home/ppetraki/Sandbox/Games/nana-creator/src/filemanager.cpp: In function ‘std::__cxx11::string get_working_dir()’:
/home/ppetraki/Sandbox/Games/nana-creator/src/filemanager.cpp:140:15: warning: ignoring return value of ‘char* getcwd(char*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  GetCurrentDir(buff, FILENAME_MAX);
               ^
[ 98%] Linking CXX executable test-ctrls
//usr/local/lib/libnana.so: undefined reference to `XcursorLibraryLoadCursor'
//usr/local/lib/libnana.so: undefined reference to `XcursorFilenameLoadCursor'
collect2: error: ld returned 1 exit status
CMakeFiles/test-ctrls.dir/build.make:83: recipe for target 'test-ctrls' failed
make[2]: *** [test-ctrls] Error 1
CMakeFiles/Makefile2:645: recipe for target 'CMakeFiles/test-ctrls.dir/all' failed
make[1]: *** [CMakeFiles/test-ctrls.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable nana-creator
[100%] Built target nana-creator
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ppetraki** [comment]
If you want something simpler to maintain then go all in with meson. My merge proposal only supports UNIX but it wouldn't take that much more to make it cross platform with 1/5 the code compared to the cmake implementation.

Unlike cmake, meson tells you when your variables are empty.

On the other hand, Nana has already done all the work for cross platform cmake dependency resolution. The path of least resistance would be integrate and sync with his upstream build configuration. You're likely missing the lib paths due to not using FindX11. 

https://github.com/cnjinhao/nana/tree/master/build/cmake

**Comment by ppetraki** [comment]
This issue is no longer relevant thanks to pull #11. Closing
